### ISSUE TITLE
Devel Detection - multiple boxes in same target

### ISSUE THREAD

**Issue by duda1202** [zhanghanduo/cubicle_detect#5]
Hi,

I have been using the devel version you released and there is a small issue. It creates multiple bounding boxes for the same target, so tracking also creates multiple unique ids for the same person. Do you know what could be the cause of this? Also, unrelated, do you have any articles you wrote about this so I can cite on my thesis? Thank you for your time.

**Comment by duda1202** [comment]
Issue occurs when using any other yolo cfg and weights besides bdd. But with bdd the bounding box is working fine

edit: meant spp, not bdd

**Comment by zhanghanduo** [comment]
Recommended method is spp.cfg and spp.weights. Bdd is also ok. I think the problem is you also need to change the nms threshold (default is 0.3) accordingly when you switch other cfgs in config/yolov3_spp.yaml or yolov3_bdd.yaml. If you find multiple targets, then try to enlarge the value and check whether the issue is less serious. Anyway just tune that value.

**Comment by duda1202** [comment]
At least with Yolo v3-tiny, that method does not work. While it improves a bit, I had to put the threshold up to 0.8 to lower the number of boxes in the same person.

**Comment by zhanghanduo** [comment]
PS: The paper you can cite:

Karunasekera, Hasith, Han Wang, and Handuo Zhang. "Multiple Object Tracking with attention to Appearance, Structure, Motion and Size." IEEE Access (2019).

@article{karunasekera2019multiple,
  title={Multiple Object Tracking with attention to Appearance, Structure, Motion and Size},
  author={Karunasekera, Hasith and Wang, Han and Zhang, Handuo},
  journal={IEEE Access},
  year={2019},
  publisher={IEEE}
}
